In [28]:
import numpy as np

In [2]:
lists = [1,2,3,4]
lists

[1, 2, 3, 4]

In [5]:
a = np.array(lists)

In [6]:
a

array([1, 2, 3, 4])

In [4]:
print(1==1)

True


In [8]:
print(lists==a)

[array([ True,  True,  True,  True])]


In [11]:
arr = np.linspace(1,5, 4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [26]:
np.random.rand(10)

array([0.36179146, 0.68948468, 0.76287214, 0.34668834, 0.60445941,
       0.12413565, 0.43145581, 0.74124808, 0.64540465, 0.33340868])

In [40]:
arr = np.arange(1, 21).reshape(4,5)

In [41]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
arr[2:, 3:]

array([[14, 15],
       [19, 20]])

In [45]:
arr[0:2, 2:4]

array([[3, 4],
       [8, 9]])